# TimesNet
# python run.py --learning_rate 0.001 --is_training 1 --root_path ./dataset/ --data_path PJM_OT_data.csv --model_id PJM --model TimesNet --data PJM_OT --pjm_sub_name AE --features MS --seq_len 7 --label_len 2 --pred_len 1 --e_layers 1 --d_layers 1 --factor 2 --enc_in 19 --dec_in 10 --c_out 10 --d_model 128 --d_ff 64 --des 'Exp' --itr 1 --top_k 5  --sub_train --time_train
python run.py --learning_rate 0.001 --is_training 1 --root_path ./dataset/ --data_path PJM_OT_data.csv --model_id PJM --model TimesNet --data PJM_OT --pjm_sub_name AEP --features MS --seq_len 7 --label_len 2 --pred_len 1 --e_layers 1 --d_layers 1 --factor 2 --enc_in 19 --dec_in 10 --c_out 10 --d_model 128 --d_ff 64 --des 'Exp' --itr 1 --top_k 5 --sub_train --time_train 
python run.py --learning_rate 0.001 --is_training 1 --root_path ./dataset/ --data_path PJM_OT_data.csv --model_id PJM --model TimesNet --data PJM_OT --pjm_sub_name AP --features MS --seq_len 7 --label_len 2 --pred_len 1 --e_layers 1 --d_layers 1 --factor 2 --enc_in 19 --dec_in 10 --c_out 10 --d_model 128 --d_ff 64 --des 'Exp' --itr 1 --top_k 5 --sub_train --time_train
python run.py --learning_rate 0.001 --is_training 1 --root_path ./dataset/ --data_path PJM_OT_data.csv --model_id PJM --model TimesNet --data PJM_OT --pjm_sub_name ATSI --features MS --seq_len 7 --label_len 2 --pred_len 1 --e_layers 1 --d_layers 1 --factor 2 --enc_in 19 --dec_in 10 --c_out 10 --d_model 128 --d_ff 64 --des 'Exp' --itr 1 --top_k 5 --sub_train --time_train
python run.py --learning_rate 0.001 --is_training 1 --root_path ./dataset/ --data_path PJM_OT_data.csv --model_id PJM --model TimesNet --data PJM_OT --pjm_sub_name BC --features MS --seq_len 7 --label_len 2 --pred_len 1 --e_layers 1 --d_layers 1 --factor 2 --enc_in 19 --dec_in 10 --c_out 10 --d_model 128 --d_ff 64 --des 'Exp' --itr 1 --top_k 5 --sub_train --time_train
python run.py --learning_rate 0.001 --is_training 1 --root_path ./dataset/ --data_path PJM_OT_data.csv --model_id PJM --model TimesNet --data PJM_OT --pjm_sub_name CE --features MS --seq_len 7 --label_len 2 --pred_len 1 --e_layers 1 --d_layers 1 --factor 2 --enc_in 19 --dec_in 10 --c_out 10 --d_model 128 --d_ff 64 --des 'Exp' --itr 1 --top_k 5 --sub_train --time_train
python run.py --learning_rate 0.001 --is_training 1 --root_path ./dataset/ --data_path PJM_OT_data.csv --model_id PJM --model TimesNet --data PJM_OT --pjm_sub_name DAY --features MS --seq_len 7 --label_len 2 --pred_len 1 --e_layers 1 --d_layers 1 --factor 2 --enc_in 19 --dec_in 10 --c_out 10 --d_model 128 --d_ff 64 --des 'Exp' --itr 1 --top_k 5 --sub_train --time_train
python run.py --learning_rate 0.001 --is_training 1 --root_path ./dataset/ --data_path PJM_OT_data.csv --model_id PJM --model TimesNet --data PJM_OT --pjm_sub_name DEOK --features MS --seq_len 7 --label_len 2 --pred_len 1 --e_layers 1 --d_layers 1 --factor 2 --enc_in 19 --dec_in 10 --c_out 10 --d_model 128 --d_ff 64 --des 'Exp' --itr 1 --top_k 5 --sub_train --time_train
python run.py --learning_rate 0.001 --is_training 1 --root_path ./dataset/ --data_path PJM_OT_data.csv --model_id PJM --model TimesNet --data PJM_OT --pjm_sub_name DOM --features MS --seq_len 7 --label_len 2 --pred_len 1 --e_layers 1 --d_layers 1 --factor 2 --enc_in 19 --dec_in 10 --c_out 10 --d_model 128 --d_ff 64 --des 'Exp' --itr 1 --top_k 5 --sub_train --time_train
python run.py --learning_rate 0.001 --is_training 1 --root_path ./dataset/ --data_path PJM_OT_data.csv --model_id PJM --model TimesNet --data PJM_OT --pjm_sub_name DPL --features MS --seq_len 7 --label_len 2 --pred_len 1 --e_layers 1 --d_layers 1 --factor 2 --enc_in 19 --dec_in 10 --c_out 10 --d_model 128 --d_ff 64 --des 'Exp' --itr 1 --top_k 5 --sub_train --time_train
python run.py --learning_rate 0.001 --is_training 1 --root_path ./dataset/ --data_path PJM_OT_data.csv --model_id PJM --model TimesNet --data PJM_OT --pjm_sub_name DUQ --features MS --seq_len 7 --label_len 2 --pred_len 1 --e_layers 1 --d_layers 1 --factor 2 --enc_in 19 --dec_in 10 --c_out 10 --d_model 128 --d_ff 64 --des 'Exp' --itr 1 --top_k 5 --sub_train --time_train
python run.py --learning_rate 0.001 --is_training 1 --root_path ./dataset/ --data_path PJM_OT_data.csv --model_id PJM --model TimesNet --data PJM_OT --pjm_sub_name EKPC --features MS --seq_len 7 --label_len 2 --pred_len 1 --e_layers 1 --d_layers 1 --factor 2 --enc_in 19 --dec_in 10 --c_out 10 --d_model 128 --d_ff 64 --des 'Exp' --itr 1 --top_k 5 --sub_train --time_train
python run.py --learning_rate 0.001 --is_training 1 --root_path ./dataset/ --data_path PJM_OT_data.csv --model_id PJM --model TimesNet --data PJM_OT --pjm_sub_name JC --features MS --seq_len 7 --label_len 2 --pred_len 1 --e_layers 1 --d_layers 1 --factor 2 --enc_in 19 --dec_in 10 --c_out 10 --d_model 128 --d_ff 64 --des 'Exp' --itr 1 --top_k 5 --sub_train --time_train
python run.py --learning_rate 0.001 --is_training 1 --root_path ./dataset/ --data_path PJM_OT_data.csv --model_id PJM --model TimesNet --data PJM_OT --pjm_sub_name ME --features MS --seq_len 7 --label_len 2 --pred_len 1 --e_layers 1 --d_layers 1 --factor 2 --enc_in 19 --dec_in 10 --c_out 10 --d_model 128 --d_ff 64 --des 'Exp' --itr 1 --top_k 5 --sub_train --time_train
python run.py --learning_rate 0.001 --is_training 1 --root_path ./dataset/ --data_path PJM_OT_data.csv --model_id PJM --model TimesNet --data PJM_OT --pjm_sub_name PE --features MS --seq_len 7 --label_len 2 --pred_len 1 --e_layers 1 --d_layers 1 --factor 2 --enc_in 19 --dec_in 10 --c_out 10 --d_model 128 --d_ff 64 --des 'Exp' --itr 1 --top_k 5 --sub_train --time_train
python run.py --learning_rate 0.001 --is_training 1 --root_path ./dataset/ --data_path PJM_OT_data.csv --model_id PJM --model TimesNet --data PJM_OT --pjm_sub_name PEP --features MS --seq_len 7 --label_len 2 --pred_len 1 --e_layers 1 --d_layers 1 --factor 2 --enc_in 19 --dec_in 10 --c_out 10 --d_model 128 --d_ff 64 --des 'Exp' --itr 1 --top_k 5 --sub_train --time_train
python run.py --learning_rate 0.001 --is_training 1 --root_path ./dataset/ --data_path PJM_OT_data.csv --model_id PJM --model TimesNet --data PJM_OT --pjm_sub_name PL --features MS --seq_len 7 --label_len 2 --pred_len 1 --e_layers 1 --d_layers 1 --factor 2 --enc_in 19 --dec_in 10 --c_out 10 --d_model 128 --d_ff 64 --des 'Exp' --itr 1 --top_k 5 --sub_train --time_train
python run.py --learning_rate 0.001 --is_training 1 --root_path ./dataset/ --data_path PJM_OT_data.csv --model_id PJM --model TimesNet --data PJM_OT --pjm_sub_name PN --features MS --seq_len 7 --label_len 2 --pred_len 1 --e_layers 1 --d_layers 1 --factor 2 --enc_in 19 --dec_in 10 --c_out 10 --d_model 128 --d_ff 64 --des 'Exp' --itr 1 --top_k 5 --sub_train --time_train
python run.py --learning_rate 0.001 --is_training 1 --root_path ./dataset/ --data_path PJM_OT_data.csv --model_id PJM --model TimesNet --data PJM_OT --pjm_sub_name PS --features MS --seq_len 7 --label_len 2 --pred_len 1 --e_layers 1 --d_layers 1 --factor 2 --enc_in 19 --dec_in 10 --c_out 10 --d_model 128 --d_ff 64 --des 'Exp' --itr 1 --top_k 5 --sub_train --time_train

